Exploring the datasets from last semester project done by Marta Kuziora.

In [6]:
import numpy as np
import pandas as pd
from langdetect import detect
import matplotlib.pyplot as plt
import time

filepath = "../../kaggleDataset/marta_datasets/"

In [7]:
artists_df = pd.read_csv(filepath + 'artist_features.csv')
artists_df.head()

,_id,followers,mb_id,popularity,reduced_genres,gender,type,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,tfidf
0,3XSyTI9ct70ZheMESAv2st,3752.0,290e5513-55d3-426f-a4ba-1ac3ce589107,61.0,['broadway'],2,Person,0.5459,0.44010,6.4,-9.4249,0.8,0.14020,0.756500,3.180000e-07,0.15880,0.6575,125.3684,153180.0,NaN
1,2jYHSJBXjusgmYdrNeaRmg,1361.0,09cddf26-fe4a-493e-bb1d-64723892ed8d,29.0,['jazz'],2,Person,0.6975,0.55410,5.8,-11.2578,0.4,0.04146,0.311739,7.196700e-01,0.09388,0.6947,103.1691,324042.8,NaN
2,5LmehwqsJa7a4Ya5SaqXpx,1147.0,ca3f3ee1-c4a7-4bac-a16a-0b888a396c6b,37.0,['doo-wop'],0,Group,0.5071,0.55695,6.1,-10.1384,1.0,0.06511,0.726900,9.358214e-02,0.20124,0.8238,139.8446,141725.6,NaN
3,10BFTSAfLauhKVmdby4zac,0.0,3a8ecc10-f888-48c0-9674-5c0ccd1fe93f,0.0,[],0,Group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4hwEAtCJZa1LMgbuRpUWJB,4.0,ca3f3ee1-c4a7-4bac-a16a-0b888a396c6b,0.0,[],0,Group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
artist_songs_df = pd.read_csv(filepath + 'artist_songs.csv')
artist_songs_df.head()

,_id,followers,mb_id,popularity,reduced_genres,gender,type,begin_date_year,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,3XSyTI9ct70ZheMESAv2st,3752.0,290e5513-55d3-426f-a4ba-1ac3ce589107,61.0,['broadway'],2,Person,1980.0,0.5459,0.44010,6.4,-9.4249,0.8,0.14020,0.756500,3.180000e-07,0.15880,0.6575,125.3684,153180.0
1,2jYHSJBXjusgmYdrNeaRmg,1361.0,09cddf26-fe4a-493e-bb1d-64723892ed8d,29.0,['jazz'],2,Person,1960.0,0.6975,0.55410,5.8,-11.2578,0.4,0.04146,0.311739,7.196700e-01,0.09388,0.6947,103.1691,324042.8
2,5LmehwqsJa7a4Ya5SaqXpx,1147.0,ca3f3ee1-c4a7-4bac-a16a-0b888a396c6b,37.0,['doo-wop'],0,Group,1956.0,0.5071,0.55695,6.1,-10.1384,1.0,0.06511,0.726900,9.358214e-02,0.20124,0.8238,139.8446,141725.6
3,10BFTSAfLauhKVmdby4zac,0.0,3a8ecc10-f888-48c0-9674-5c0ccd1fe93f,0.0,[],0,Group,1965.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4hwEAtCJZa1LMgbuRpUWJB,4.0,ca3f3ee1-c4a7-4bac-a16a-0b888a396c6b,0.0,[],0,Group,1956.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
dataset_df = pd.read_csv(filepath + 'dataset.csv')
print("Number of artists: {}".format(len(dataset_df)))
dataset_df.head()

Number of artists: 739298

,Unnamed: 0,_id,followers,genres,mb_id,name,popularity,reduced_genres,gender,type
0,0,3XSyTI9ct70ZheMESAv2st,3752.0,['broadway'],290e5513-55d3-426f-a4ba-1ac3ce589107,Zachary Levi,61.0,['broadway'],Male,Person
1,1,2jYHSJBXjusgmYdrNeaRmg,1361.0,"['jazz guitar', 'smooth jazz']",09cddf26-fe4a-493e-bb1d-64723892ed8d,Zachary Breaux,29.0,['jazz'],Male,Person
2,2,5LmehwqsJa7a4Ya5SaqXpx,1147.0,['doo-wop'],ca3f3ee1-c4a7-4bac-a16a-0b888a396c6b,The Silhouettes,37.0,['doo-wop'],unknown,Group
3,3,10BFTSAfLauhKVmdby4zac,0.0,[],3a8ecc10-f888-48c0-9674-5c0ccd1fe93f,Peter & the Silhouettes,0.0,[],unknown,Group
4,4,4hwEAtCJZa1LMgbuRpUWJB,4.0,[],ca3f3ee1-c4a7-4bac-a16a-0b888a396c6b,The Lost Silhouettes,0.0,[],unknown,Group

In [18]:
artist_song_features_df = pd.read_csv(filepath + 'artist_song_features.csv')
artist_song_features_df.head()

,Unnamed: 0,artist_id,song_id,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,0,3XSyTI9ct70ZheMESAv2st,1yh793k8lDYfXv3DhHaIXC,0.236,0.162,5.0,-14.536,1.0,0.0305,0.842,0.000002,0.0739,0.230,91.430,222120.0
1,2,3XSyTI9ct70ZheMESAv2st,0TCt7OFRdD8PQ6vTRQxNgQ,0.625,0.567,4.0,-7.385,1.0,0.1040,0.596,0.000000,0.1990,0.882,134.169,191413.0
2,6,3XSyTI9ct70ZheMESAv2st,0d2yIwPD2dLNFqrOye5qN2,0.529,0.477,8.0,-8.237,1.0,0.2120,0.736,0.000000,0.0434,0.452,123.500,170093.0
3,7,3XSyTI9ct70ZheMESAv2st,2xB0yPkGvwuPXiaOVHYnwX,0.438,0.364,2.0,-12.162,1.0,0.0496,0.715,0.000000,0.1070,0.792,166.378,179800.0
4,8,3XSyTI9ct70ZheMESAv2st,74VcKerwPq5WSOkXSCZ6vi,0.525,0.571,6.0,-8.935,0.0,0.1550,0.607,0.000000,0.2240,0.932,171.027,105160.0

In [19]:
songs_lyrics_df = pd.read_csv(filepath + 'songs_lyrics.csv')
print("Number of songs: {}".format(len(songs_lyrics_df)))
songs_lyrics_df.head()

Number of songs: 225654

,Unnamed: 0,artist_id,mb_id,artist_name,tid,title,tid_mxm_x,tid_mxm_y,words
0,10,AR002UA1187B9A637D,7752a11c-9d8b-4220-ac44-e4a04cc8471d,The Bristols,TRAFPWS12903CDF737,I'll Be Gone,3549344.0,3549344,"1:22,2:4,3:28,4:2,5:1,6:3,7:13,8:3,9:16,10:2,1..."
1,14,AR002UA1187B9A637D,7752a11c-9d8b-4220-ac44-e4a04cc8471d,The Bristols,TREKDCH128F92EBFDC,Can't You See That He's Mine,3701180.0,3701180,"1:9,2:3,3:8,4:5,5:9,6:4,7:3,8:5,9:10,11:2,12:2..."
2,74,AR00A6H1187FB5402A,312c14d9-7897-4608-944a-c5b1c76ae682,The Meatmen,TRTFZQL12903CB84FC,Me 262 (Originally Performed by Blue Oyster Cult),3354738.0,3354738,"2:1,3:3,4:1,5:1,6:1,7:1,10:1,11:1,12:3,13:1,14..."
3,75,AR00A6H1187FB5402A,312c14d9-7897-4608-944a-c5b1c76ae682,The Meatmen,TRLHFUR12903CB852D,I'm a Bug (Originally Performed by The Urinals),6458608.0,6458608,"1:3,2:1,3:3,4:2,6:4,7:1,8:1,9:5,10:1,14:1,15:6..."
4,76,AR00A6H1187FB5402A,312c14d9-7897-4608-944a-c5b1c76ae682,The Meatmen,TRSCFMS12903CB84ED,Meatman (Originally Performed by Jerry Lee Lewis),668965.0,668965,"1:4,2:27,4:7,5:5,6:5,7:2,8:6,9:1,10:4,11:2,12:..."